### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by AntoineSoetewey** [laymonage/giscus#100]
Hello,

There is a small typo: Sign in to instead of Sign into

<img width="828" alt="Screenshot 2021-06-03 at 19 55 47" src="https://user-images.githubusercontent.com/17910063/120690731-e07f0200-c4a5-11eb-98c4-065f9ee88d68.png">

Thanks!

**Comment by laymonage** [comment]
@AntoineSoetewey Thanks, and thanks for switching to giscus!
