### ISSUE TITLE
Add support to only allow specific origins

### ISSUE THREAD

**Issue by laymonage** [laymonage/giscus#104]
Utterances supports origin allowlisting using [`utterances.json`](https://github.com/utterance/utterances/blob/master/utterances.json). This is helpful to prevent unknown sites from using giscus with any user's repository discussions.

**Comment by laymonage** [comment]
https://stackoverflow.com/questions/62412608/how-do-i-get-file-contents-from-github-apiv4-on-the-default-branch

```graphql
{
  repository(owner: $owner, name: $name) {
    object(expression: "HEAD:giscus.json") {
      ... on Blob {
        text
      }
    }
  }
}
```

This would help us prevent something like https://github.com/utterance/utterances/issues/523.

**Comment by laymonage** [comment]
Looks like we don't need to use the GraphQL API.

We can just call something like

https://api.github.com/repos/laymonage/giscus/contents/README.md

and get decode the content.

**Comment by samarulmeu** [comment]
Sorry for the, probably, dumb question, but does it already exists a way to specify that I can allow only my `http://example.com` site to post and read comments?

**Comment by laymonage** [comment]
@samarulmeu Hey, no, that's a good question. I'm still working on the feature, it's nearly done. I'm looking to push it this weekend.

**Comment by laymonage** [comment]
Sorry for the delay @samarulmeu, I was feeling unwell. It's implemented in #125, please test it when you have the time. Thanks!

**Comment by samarulmeu** [comment]
@laymonage Thank you so much! This is a great news. I was waiting for this before implementing it on my blog.

I will test it tomorrow.

Take care of your health. It is the most important.

**Comment by samarulmeu** [comment]
Please tell me if I did something wrong.

You can see the giscus.json file [here](https://github.com/samarulmeu/cttrl_comments), but I can still post comments from other domains (https://cttrl-git-fixednav-samarul.vercel.app).

**Comment by laymonage** [comment]
Hey @samarulmeu, thanks for the report.
I've shipped https://github.com/laymonage/giscus/commit/de316dcabfd0c54367bd812000f17daa3c39da62 which should fix the issue.

![image](https://user-images.githubusercontent.com/6379424/124383710-23780380-dcf8-11eb-85a6-0713837f3a1c.png)

**Comment by samarulmeu** [comment]
Thank you! Now it is working. I tested even  the regex (the giscus example) and it is working.
