### ISSUE TITLE
Giscus fails when repository contains capitals

### ISSUE THREAD

**Issue by SeanKilleen** [laymonage/giscus#118]
Discovered this when using Giscus with Jekyll as part of https://github.com/mmistakes/minimal-mistakes/pull/3022

The PR takes the repository name from a setting, which in my case was `SeanKilleen/seankilleen.github.io`. 

Giscus failed with a 400 error when retrieving comments, so thought there was no discussion topic, and therefore kept creating new discussion topics.

I think the issue is that the GitHub API or similar might be failing with a repo name that contains uppercase characters. I'll see if I can submit a PR to make that behavior case insensitive.

**Comment by SeanKilleen** [comment]
After looking through the code, I think I can see where the errant calls are being made, but I'm not sure where the appropriate place would be to address it. Happy to do a PR if given a few pointers; also happy for anyone else to tackle it.

**Comment by laymonage** [comment]
Hey @SeanKilleen , thanks for the report. Looking at your PR, I saw this line:

```js
script.setAttribute('data-repo', '{{ site.repository | downcase }}');
```

Is it possible that this is caused by the `| downcase`? If GitHub's API is case-sensitive, then I think you shouldn't transform the repository name to lowercase. There's no way for giscus to know the correct casing of the repository name unless you specify it correctly.

**Comment by SeanKilleen** [comment]
@laymonage the downcase was the fix in this case. Without the `downcase` which convert things to lowercase, the repo was passed as `SeanKilleen/seankilleen.github.io`, which caused the issue in the `giscuss.app/api` call. As soon as I added the `downcase`, the API call no longer failed and giscus operated as expected.

**Comment by LazyRen** [comment]
As I try to migrate from utterances to giscus, I have failed to pass [giscus] configuration with below error.
`Cannot use giscus in this repository. Make sure all of the above criteria has been met.`

I already finished 3 steps. So I'm guessing this might be the cause of the false negative? (with repo name `LazyRen/LazyRen.github.io`).

Looking forward for a fix here if possible.

[giscus]: https://giscus.vercel.app

**Comment by laymonage** [comment]
Thanks for the report, I'll try to fix this later today.

**Comment by laymonage** [comment]
@LazyRen It turns out that the issue is unrelated, I've shipped https://github.com/laymonage/giscus/commit/bca513c72a5a3b309cce4a864b042a2e82c66c48 which should fix it.

@SeanKilleen I cannot reproduce the error, the following works fine: https://giscus.app/widget?repo=SeanKilleen/seankilleen.github.io&term=test/layout/uncategorized/layout-comments/

Could you copy the `<iframe>`'s src when it happens and paste it here?

**Comment by SeanKilleen** [comment]
@laymonage repro:

## With the capitalized repo name

`src="https://giscus.app/widget?origin=http%3A%2F%2F127.0.0.1%3A4000%2Ftest%2Flayout%2Funcategorized%2Flayout-comments%2F&session=&theme=light&reactionsEnabled=1&repo=SeanKilleen%2Fseankilleen.github.io&repoId=MDEwOlJlcG9zaXRvcnkyNDg1MTcxNQ%3D%3D&category=MinimalMistakesPR&categoryId=MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMzMDYwNTMx&description=This+post+should+display+comments.&term=test%2Flayout%2Funcategorized%2Flayout-comments%2F"`

Loading the page in Chrome for an existing discussion

> ![image](https://user-images.githubusercontent.com/2148318/124340230-c5291480-db81-11eb-8f2a-2b9ebc4dd43d.png)

## When Changing the repository ID to lowercase and no other changes

`src="https://giscus.app/widget?origin=http%3A%2F%2F127.0.0.1%3A4000%2Ftest%2Flayout%2Funcategorized%2Flayout-comments%2F&session=&theme=light&reactionsEnabled=1&repo=seankilleen%2Fseankilleen.github.io&repoId=MDEwOlJlcG9zaXRvcnkyNDg1MTcxNQ%3D%3D&category=MinimalMistakesPR&categoryId=MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMzMDYwNTMx&description=This+post+should+display+comments.&term=test%2Flayout%2Funcategorized%2Flayout-comments%2F"`

Discussions load as expected:

> ![image](https://user-images.githubusercontent.com/2148318/124340435-41702780-db83-11eb-80a5-2411b4bb160e.png)

## Comparing the two iFrame SRCs

BeyondCompare says the only difference is the capitalization: 

> ![image](https://user-images.githubusercontent.com/2148318/124340558-07535580-db84-11eb-968e-d071b7f2e18b.png)

> ![image](https://user-images.githubusercontent.com/2148318/124340566-120dea80-db84-11eb-9ab8-77c8643005b7.png)

**Comment by laymonage** [comment]
Thanks @SeanKilleen, looks like there's a bug in GitHub when you're including the category in the query.

See:

- lowercase, with category:
  https://github.com/search?type=discussions&q=repo%3Aseankilleen%2Fseankilleen.github.io+category%3A%22MinimalMistakesPR%22+in%3Atitle+test%2Flayout%2Funcategorized%2Flayout-comments%2F
- correct case, with category:
  https://github.com/search?type=discussions&q=repo%3ASeanKilleen%2Fseankilleen.github.io+category%3A%22MinimalMistakesPR%22+in%3Atitle+test%2Flayout%2Funcategorized%2Flayout-comments%2F
- lowercase, without category:
  https://github.com/search?type=discussions&q=repo%3Aseankilleen%2Fseankilleen.github.io+in%3Atitle+test%2Flayout%2Funcategorized%2Flayout-comments%2F
- correct case, without category:
  https://github.com/search?type=discussions&q=repo%3ASeanKilleen%2Fseankilleen.github.io+in%3Atitle+test%2Flayout%2Funcategorized%2Flayout-comments%2F

Might be related to a bug I reported earlier: https://github.com/github/feedback/discussions/4113

I've shipped https://github.com/laymonage/giscus/commit/bd4379ed4e8a4bdb8d2b454bcc7e20eb0fe8df55, please let me know if that fixes it.

**Comment by SeanKilleen** [comment]
@laymonage confirmed -- #124  resolved this issue. 👍 Thanks!
