### ISSUE TITLE
Add event listener for when preferred_color_scheme changes.

### ISSUE THREAD

**Issue by ceiphr** [laymonage/giscus#120]
Right now, on page load, preferred_color_scheme respects the system color scheme. 

But, what if you're on a device that changes the system color scheme automatically? In those cases, giscus does not update and requires a page reload to continue respecting the system color scheme.

You could potentially solve this by using `addEventListener` to apply state changes like so:

```tsx
const [mQuery, setMQuery] = React.useState<string>("light")

React.useEffect(() => {
  let mediaQuery = window.matchMedia("(prefers-color-scheme: dark)")

  // Listening for changes.
  mediaQuery.addEventListener("change", e => {
    setMQuery(e.matches ? "dark" : "light")
  })

  // On initial load.
  setMQuery(mediaQuery.matches ? "dark" : "light")
}
```

FYI, that code snippet is untested.

**Comment by laymonage** [comment]
Thanks @ceiphr, I've shipped https://github.com/laymonage/giscus/commit/469980ef86d787b2f5e70f5a9804a64d37bb90d8, please let me know if that fixes the issue.

**Comment by ceiphr** [comment]
That works flawlessly! Thank you!
