### ISSUE TITLE
More granular configuration of reactions

### ISSUE THREAD

**Issue by kunigami** [laymonage/giscus#121]
I'd love to be able to hide the text "XX reactions". Could we consider exposing that? I can't seem to do it via CSS due to iframe cross-domain.

Perhaps a way to take inline CSS? Should I develop a new theme instead?

**Comment by laymonage** [comment]
Hey, thanks for the suggestion. I'm planning to add custom CSS support, so this should be possible when that lands.

**Comment by laymonage** [comment]
@kunigami Hey, I've added custom CSS support in #128. You can hide the reactions count using the following CSS rule:

```css
.gsc-reactions-count {
  display: none;
}
```

You can read [this guide](https://github.com/laymonage/giscus/blob/main/ADVANCED-USAGE.md#data-theme) and [this guide](https://github.com/laymonage/giscus/blob/main/CONTRIBUTING.md#creating-new-themes) for more details.
