### ISSUE TITLE
giscus.app refused to connect

### ISSUE THREAD

**Issue by garfield786** [laymonage/giscus#151]
![image](https://user-images.githubusercontent.com/5808449/127242249-5b76fb63-a7e3-4ec4-b9eb-46779acf6324.png)

I get the following error when I added the script tag, please check garfield786.github.io

**Comment by garfield786** [comment]
Found the issue. It was not able to connect because of the title tag

**Comment by nobodyme** [comment]
I'm having the same issue when using [giscus-react](https://www.npmjs.com/package/@giscus/react), what exactly fixed it for you?
