### ISSUE TITLE
giscus is not installed on this repository issue ?

### ISSUE THREAD

**Issue by imyounas** [laymonage/giscus#160]
Hi,

I have installed giscus app and has given access to my public repository. but when I try to load comments or try this URL , 
https://giscus.app/api/discussions?repo=https://github.com/imyounas/wic-giscuss&term=blog/new-features-in-v1&category=announcements&number=0&last=15

I get error {"error":"giscus is not installed on this repository"}.

here is my confg:

     data-repo= https://github.com/imyounas/wic-giscuss.git,
     data-repo-id= 392519539,
      data-category= announcements,
      data-category-id= announcements,

Can you plz guide, what is I am doing wrong here ?

Thanks,
Imran

**Comment by laymonage** [comment]
@imyounas The repo should be in the format of `owner/repo`, e.g. `imyounas/wc-giscuss`.

**Comment by Imran-hd** [comment]
Thanks, Yes it solved the problem.
By the way do I need 'data-category-id'  and how can I get it ?

**Comment by imyounas** [comment]
Thanks. It solved the problem. 
By the way do I need 'data-category-id' , and how to get it ?

**Comment by laymonage** [comment]
@imyounas Follow the instructions on the main page and select the discussion category, you will get the value at the end of the guide.

![Enter repository owner/name](https://user-images.githubusercontent.com/6379424/127306701-4b539cb3-fa95-4ac4-8a83-8f3609a0596a.png)

![Select the category](https://user-images.githubusercontent.com/6379424/127306665-46c28817-a16e-48a7-abb3-4dd70a3802cd.png)

![See the config values](https://user-images.githubusercontent.com/6379424/127306473-7fceb0cf-e153-476a-87c5-2cb23093fdaf.png)
