### ISSUE TITLE
Support QnA-enabled category?

### ISSUE THREAD

**Issue by laymonage** [laymonage/giscus#38]
When creating a discussion category, there's an option to make it an "Open ended discussion" vs "Question / Answer". Discussions created in the latter category would have StackOverflow-style "selected answer" and other features enabled.

I don't know if this makes sense if we're embedding the discussion's comments on a webpage, though. I mean, we don't even include the discussion content itself, so...

**Comment by wgyt** [comment]
I don’t think that this would make much sense unless you were trying to clone StackOverflow

**Comment by laymonage** [comment]
@wgyt Yup, I agree. Thanks.

Closing this for now.
