### ISSUE TITLE
The busy spinner keeps turning without end

### ISSUE THREAD

**Issue by sirinath** [laymonage/giscus#69]
Once you enter the repo the busy spinner does not stop and nothing happens.

![image](https://user-images.githubusercontent.com/637415/118365034-a910ea00-b5b8-11eb-8219-bcc639ec1caa.png)

**Comment by laymonage** [comment]
Thanks for reporting the issue! I'll look into this. It doesn't happen for other repositories, though. Have you installed the [app](https://github.com/laymonage/giscus) on the repository?

**Comment by sirinath** [comment]
I have installed in in my account for all repositories. This saves me from configuring it for other repos later.

**Comment by laymonage** [comment]
@sirinath I've pushed a potential fix. Could you try again?

**Comment by sirinath** [comment]
Works! That was fast!
