### ISSUE TITLE
Link to the discussion

### ISSUE THREAD

**Issue by sirinath** [laymonage/giscus#70]
Please add a link to the discussion some where at the top so the user can visit the actual discussion itself.

![image](https://user-images.githubusercontent.com/637415/118365376-25f09380-b5ba-11eb-9b90-b0c7a247b1a5.png)

**Comment by laymonage** [comment]
Thanks! I've turned the `comments` count into a link to the discussion (if it exists).

**Comment by sirinath** [comment]
Super.

**Comment by szpak** [comment]
Works great. I've just wanted to write to @sirinath that it works :).
