### ISSUE TITLE
Issues with iFrameSize and width

### ISSUE THREAD

**Issue by ojacques** [laymonage/giscus#76]
First, superb project - thanks!

I have an issue with the width of the giscus iFrame, where it only takes what looks to be 25% of the available width. Is there a way to control that?

![image](https://user-images.githubusercontent.com/5385290/118776815-ac41f980-b888-11eb-8964-2e9cb7099de4.png)

- Example: https://www.olivierjacques.com/TDBwebsite/episode6/
- Source: (hugo based): https://github.com/ojacques/TDBwebsite, with the [commit to add Giscus](https://github.com/ojacques/TDBwebsite/commit/24fff5bbd6ed466f69de3c22a9953748d6ac1536)

I'm not an HTML guru, but it looks to be something around iFrameResizer?

![image](https://user-images.githubusercontent.com/5385290/118777404-4e61e180-b889-11eb-8e5b-62357e7d9382.png)

![image](https://user-images.githubusercontent.com/5385290/118777485-66d1fc00-b889-11eb-8ef2-506032291481.png)

**Comment by laymonage** [comment]
Hi @ojacques, thanks for raising the issue!

iFrameResizer only handles the automatic height resizing of the iframe based on the contents.

giscus adds the `giscus` class to the `<div>` that wraps the `<iframe>`,  and it also adds the `giscus-frame` class to the `<iframe>` element. You can use that as the extension points for customizations.

For example, something like this in your CSS should work:

```css
.giscus, .giscus-frame {
    width: 100%;
}
```

It's nothing magical, so you can also apply any styles you want to the wrapper and iframe, e.g. `flex-basis: 100%`.

You can also limit the height as you wish.

Example:

I added the following rules:

![image](https://user-images.githubusercontent.com/6379424/118782189-0e662300-b8b8-11eb-97bd-960fefb0bb14.png)

![image](https://user-images.githubusercontent.com/6379424/118782229-1756f480-b8b8-11eb-90e5-4827ce0027e3.png)

Result:

![image](https://user-images.githubusercontent.com/6379424/118782135-f9898f80-b8b7-11eb-9d3c-7d28d2dc3f91.png)

**Comment by ojacques** [comment]
Brilliant, thanks!
