### ISSUE TITLE
Vercel.app is mostly inaccessible from Mainland China

### ISSUE THREAD

**Issue by vaparo** [laymonage/giscus#91]
Is it possible to switch to other services?

**Comment by laymonage** [comment]
@vaparo Is it just the domain? If so, I've already moved the domain to https://giscus.app. Otherwise, I'll also try to host it on Netlify.

**Comment by vaparo** [comment]
@laymonage https://giscus.app is also inaccessible.

**Comment by laymonage** [comment]
Sorry, I don't think there's much I can do here. I just checked that it seems Netlify is also blocked in China. Do you have recommendations of similar platforms that aren't blocked in China?

**Comment by vaparo** [comment]
No, although api.netlify.com is blocked, netlify.app isn't blocked in China.

**Comment by laymonage** [comment]
@vaparo I've deployed it to https://giscus.netlify.app, does it work?

**Comment by vaparo** [comment]
@laymonage Yes, it works.

**Comment by wgyt** [comment]
@laymonage Vercel.app can be accessed in China, but you will need to change your DNS records. Source: https://www.vercel-status.com/incidents/r758bhbklgfd

**Comment by laymonage** [comment]
@wgyt Thanks for the pointer, but I can't seem to change it on Vercel.
![image](https://user-images.githubusercontent.com/6379424/120923634-d0f7f700-c6f9-11eb-91a1-ab14b04e0a6f.png)

I know that I can switch to other nameservers and change the records from there, but I'd rather avoid it if possible. I've filed a support ticket to Vercel.

**Comment by laymonage** [comment]
Nevermind, I was able to do it by just adding a new record. Can @vaparo confirm that https://giscus.app is accessible now?
